version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker/python-project/username
    DOCKER_REGISTRY_PASSWORD: /docker/python-project/password

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "docker.io"
      - docker build -t "docker.io/maheshnichenakolla/simple-python-flask-app:latest" .
      - docker push "docker.io/maheshnichenakolla/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"
